import React, { useState, useEffect } from 'react';
import { Car, CarProvider, Lookup } from '../types';
import { CloseIcon } from '../icons';

interface CarFormModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSave: (car: Omit<Car, 'id'> | Car) => void;
    car: Car | null;
    providerId: string;
    lookups: Lookup[];
}

const CarFormModal: React.FC<CarFormModalProps> = ({ isOpen, onClose, onSave, car, providerId, lookups }) => {
    const getInitialState = (): Car => {
        if (car) return car;
        
        // Default state for a new car
        return {
            id: '', // Will be generated by Firestore
            slug: '',
            status: "draft",
            brand: '',
            model: '',
            year: new Date().getFullYear(),
            // FIX: Type '""' is not assignable to type '"economy" | "business" | "premium" | "retro" | "limo" | "minivan" | "bus" | "cabrio"'.
            class: "economy",
            body_type: '',
            color: '',
            seats: 4,
            doors: 4,
            handover: {
                mode: "both",
                with_driver: { enabled: true },
                self_drive: { enabled: true }
            },
            car_features: [],
            pricing: {
                currency: "AZN",
                mode: "hourly",
                price: { base: 0, min_time: 1, extra_hour_fee: 0 }
            },
            coverage_cities: [],
            car_provider: { car_provider_id: providerId, name: '' },
            media: { photos: [] },
            created_at: '',
            updated_at: '',
        };
    };

    const [editedCar, setEditedCar] = useState<Car>(getInitialState());

    useEffect(() => {
        setEditedCar(getInitialState());
    }, [car, isOpen]);
    
    const carBrandLookup = lookups.find(l => l.key === 'car_brands');
    const carModelLookup = lookups.find(l => l.key === 'car_models');
    const carClassLookup = lookups.find(l => l.key === 'car_classes');
    const bodyTypeLookup = lookups.find(l => l.key === 'car_body_types');
    const colorLookup = lookups.find(l => l.key === 'car_colors');

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value, type } = e.target;
        
        let finalValue: any = value;
        if (type === 'number') {
            finalValue = value ? parseInt(value, 10) : 0;
        }

        if (name.includes('.')) {
            const [section, key] = name.split('.');
            if (section === 'pricing' && key === 'price') {
                 // Deeper nesting for pricing.price
                 const [priceSection, priceKey] = name.split('.');
                 setEditedCar(prev => ({
                    ...prev,
                    pricing: {
                        ...prev.pricing,
                        price: {
                            ...prev.pricing.price,
                            [priceKey]: finalValue
                        }
                    }
                 }));

            } else {
                setEditedCar(prev => ({
                    ...prev,
                    [section]: {
                        ...(prev as any)[section],
                        [key]: finalValue
                    }
                }));
            }
        } else {
            setEditedCar(prev => ({
                ...prev,
                [name]: finalValue
            }));
        }
    };
    
    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSave(editedCar);
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-50 p-4">
            <div className="bg-gray-800 rounded-lg shadow-2xl w-full max-w-2xl" onClick={e => e.stopPropagation()}>
                <header className="flex items-center justify-between p-4 border-b border-gray-700">
                    <h2 className="text-xl font-bold text-white">{car ? 'Редактировать автомобиль' : 'Добавить автомобиль'}</h2>
                    <button onClick={onClose} className="p-2 text-gray-400 hover:bg-gray-700 rounded-full"><CloseIcon /></button>
                </header>
                <form onSubmit={handleSubmit}>
                    <div className="p-6 space-y-4 max-h-[70vh] overflow-y-auto">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <SelectField label="Марка" name="brand" value={editedCar.brand} onChange={handleChange} options={carBrandLookup?.values || []} />
                            <SelectField label="Модель" name="model" value={editedCar.model} onChange={handleChange} options={carModelLookup?.values || []} />
                        </div>
                         <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <InputField label="Год" name="year" type="number" value={editedCar.year} onChange={handleChange} required />
                            <SelectField label="Класс" name="class" value={editedCar.class} onChange={handleChange} options={carClassLookup?.values || []} />
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                             <SelectField label="Тип кузова" name="body_type" value={editedCar.body_type} onChange={handleChange} options={bodyTypeLookup?.values || []} />
                             <SelectField label="Цвет" name="color" value={editedCar.color} onChange={handleChange} options={colorLookup?.values || []} />
                        </div>
                         <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <InputField label="Кол-во мест" name="seats" type="number" value={editedCar.seats} onChange={handleChange} />
                            <InputField label="Кол-во дверей" name="doors" type="number" value={editedCar.doors} onChange={handleChange} />
                        </div>
                        
                         <div>
                            <h4 className="text-lg font-semibold text-blue-400 mt-4 mb-2 border-t border-gray-700 pt-4">Цены</h4>
                             <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <SelectField label="Режим" name="pricing.mode" value={editedCar.pricing.mode} onChange={handleChange} options={['hourly', 'daily', 'mixed']} />
                                <InputField label="Валюта" name="pricing.currency" value={editedCar.pricing.currency} onChange={handleChange} required />
                             </div>
                              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
                                <InputField label="Базовая цена" name="pricing.price.base" type="number" value={editedCar.pricing.price?.base || 0} onChange={handleChange} />
                                <InputField label="Мин. время (ч/д)" name="pricing.price.min_time" type="number" value={editedCar.pricing.price?.min_time || 1} onChange={handleChange} />
                                <InputField label="Доп. час" name="pricing.price.extra_hour_fee" type="number" value={editedCar.pricing.price?.extra_hour_fee || 0} onChange={handleChange} />
                             </div>
                        </div>

                    </div>
                    <footer className="p-4 border-t border-gray-700 flex justify-end space-x-3">
                        <button type="button" onClick={onClose} className="px-4 py-2 rounded-md text-white bg-gray-600 hover:bg-gray-500">Отмена</button>
                        <button type="submit" className="px-4 py-2 rounded-md text-white bg-blue-600 hover:bg-blue-700">Сохранить</button>
                    </footer>
                </form>
            </div>
        </div>
    );
};

const InputField: React.FC<{ label: string, name: string, value: string | number, onChange: (e: React.ChangeEvent<HTMLInputElement>) => void, type?: string, required?: boolean }> = 
({ label, name, value, onChange, type = 'text', required = false }) => (
    <div>
        <label htmlFor={name} className="block text-sm font-medium text-gray-300 mb-1">{label}</label>
        <input id={name} name={name} type={type} value={value} onChange={onChange} required={required} className="w-full bg-gray-700 border-gray-600 rounded-md px-3 py-2 text-white" />
    </div>
);

const SelectField: React.FC<{ label: string, name: string, value: string, onChange: (e: React.ChangeEvent<HTMLSelectElement>) => void, options: string[] }> =
({ label, name, value, onChange, options }) => (
     <div>
        <label htmlFor={name} className="block text-sm font-medium text-gray-300 mb-1">{label}</label>
        <select id={name} name={name} value={value} onChange={onChange} className="w-full bg-gray-700 border-gray-600 rounded-md px-3 py-2 text-white">
            <option value="" disabled>Выберите...</option>
            {options.map(opt => <option key={opt} value={opt}>{opt}</option>)}
        </select>
    </div>
);


export default CarFormModal;